export const serverOptions = [
  { label: 'US West', value: 'US West' },
  { label: 'US East', value: 'US East' },
  { label: 'Europe West', value: 'Europe West' },
  { label: 'Europe East', value: 'Europe East' },
  { label: 'SE Asia', value: 'SE Asia' },
  { label: 'Dubai', value: 'Dubai' },
  { label: 'Australia', value: 'Australia' },
  { label: 'South Africa', value: 'South Africa' },
  { label: 'China TC Shanghai', value: 'China TC Shanghai' },
  { label: 'China UC', value: 'China UC' },
  { label: 'India', value: 'India' },
  { label: 'China TC Guangdong', value: 'China TC Guangdong' },
  { label: 'China TC Zhejiang', value: 'China TC Zhejiang' },
  { label: 'Japan', value: 'Japan' },
  { label: 'China TC Wuhan', value: 'China TC Wuhan' },
  { label: 'China UC2', value: 'China UC2' },
  { label: 'South America', value: 'South America' },
  { label: 'Russia', value: 'Russia' },
]
