const dota2 = {
  rank: {
    11: require("../Images/dota2/rank_icons/SeasonalRank1-1.png"),
    12: require("../Images/dota2/rank_icons/SeasonalRank1-2.png"),
    13: require("../Images/dota2/rank_icons/SeasonalRank1-3.png"),
    14: require("../Images/dota2/rank_icons/SeasonalRank1-4.png"),
    15: require("../Images/dota2/rank_icons/SeasonalRank1-5.png"),
    21: require("../Images/dota2/rank_icons/SeasonalRank2-1.png"),
    22: require("../Images/dota2/rank_icons/SeasonalRank2-2.png"),
    23: require("../Images/dota2/rank_icons/SeasonalRank2-3.png"),
    24: require("../Images/dota2/rank_icons/SeasonalRank2-4.png"),
    25: require("../Images/dota2/rank_icons/SeasonalRank2-5.png"),
    31: require("../Images/dota2/rank_icons/SeasonalRank3-1.png"),
    32: require("../Images/dota2/rank_icons/SeasonalRank3-2.png"),
    33: require("../Images/dota2/rank_icons/SeasonalRank3-3.png"),
    34: require("../Images/dota2/rank_icons/SeasonalRank3-4.png"),
    35: require("../Images/dota2/rank_icons/SeasonalRank3-5.png"),
    41: require("../Images/dota2/rank_icons/SeasonalRank4-1.png"),
    42: require("../Images/dota2/rank_icons/SeasonalRank4-2.png"),
    43: require("../Images/dota2/rank_icons/SeasonalRank4-3.png"),
    44: require("../Images/dota2/rank_icons/SeasonalRank4-4.png"),
    45: require("../Images/dota2/rank_icons/SeasonalRank4-5.png"),
    51: require("../Images/dota2/rank_icons/SeasonalRank5-1.png"),
    52: require("../Images/dota2/rank_icons/SeasonalRank5-2.png"),
    53: require("../Images/dota2/rank_icons/SeasonalRank5-3.png"),
    54: require("../Images/dota2/rank_icons/SeasonalRank5-4.png"),
    55: require("../Images/dota2/rank_icons/SeasonalRank5-5.png"),
    61: require("../Images/dota2/rank_icons/SeasonalRank6-1.png"),
    62: require("../Images/dota2/rank_icons/SeasonalRank6-2.png"),
    63: require("../Images/dota2/rank_icons/SeasonalRank6-3.png"),
    64: require("../Images/dota2/rank_icons/SeasonalRank6-4.png"),
    65: require("../Images/dota2/rank_icons/SeasonalRank6-5.png"),
    71: require("../Images/dota2/rank_icons/SeasonalRank7-1.png"),
    72: require("../Images/dota2/rank_icons/SeasonalRank7-2.png"),
    73: require("../Images/dota2/rank_icons/SeasonalRank7-3.png"),
    74: require("../Images/dota2/rank_icons/SeasonalRank7-4.png"),
    75: require("../Images/dota2/rank_icons/SeasonalRank7-5.png"),
    81: require("../Images/dota2/rank_icons/SeasonalRank8-1.png")
  }
};

export default dota2;
